#!/usr/bin/env python3
"""Regenerate every figure in this paper directly from archived experiment
JSONs -- no hand-typed numbers. Each figure function documents exactly which
archived file(s) it reads and which paper table/claim (if any) it visualizes.

Run from anywhere:
    python3 figures/make_figures.py
    (or)  python3 matrix-thinking/submissions/neurips-ws-2026/figures/make_figures.py

Requires: numpy, matplotlib (pure-Python analysis, no torch/GPU needed).
Outputs vector PDFs into this same `figures/` directory.

Data provenance (traced by an independent research pass before this script
was written; see the commit that added this file):
  - fig_taskd_forcerank.pdf   <- matrix-thinking/chapter2/results/overnight_snapshots/AGGREGATE_latest.json
                                 (the 991-run Task D snapshot behind Table 2, tab:taskd-m3)
  - fig_taske_depth.pdf       <- experiment-runs/2026-07-02_task_e_zdump/task_e_40k_zdump/*.json
                                 (Table 3, tab:taske-depth; predicted curve regenerated by
                                 literally importing and calling chapter2/analyze_zdump.py,
                                 not re-derived by hand)
  - fig_frontier_exactness.pdf <- experiment-runs/2026-07-02_stage0_waves/{probe_100k,probe_d48_100k,probe_d64_150k}/*.json
                                 (Table 5, tab:frontier-d4)
  - fig_eval_trunc_staircase.pdf <- experiment-runs/2026-07-02_deltanet_waves/eval_trunc/*.json
                                 (supplementary/illustrative -- see caption; NOT behind any
                                 table currently in the main text, see figures/README note
                                 in the script docstring below)

IMPORTANT SCOPING NOTE: experiment-runs/2026-07-03_deltanet_rd_waves/ (deephop,
waveA, exactness/wavegeo3) is a newer, still-running campaign reserved for a
separate full paper (per matrix-thinking/DELTANET_REALDATA_DESIGN.md and
DELTANET_RD_EXACTNESS_DESIGN.md, both dated 2026-07-03, chronologically after
everything this paper reports). This script deliberately does not read from
that directory. Do not add it here without re-checking the paper's stated
scope in sections/01_intro.tex and sections/07_discussion.tex first.
"""
from __future__ import annotations

import collections
import json
import os
import sys

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
FIG_DIR = os.path.dirname(os.path.abspath(__file__))
PAPER_DIR = os.path.dirname(FIG_DIR)                      # neurips-ws-2026/
SUBMISSIONS_DIR = os.path.dirname(PAPER_DIR)               # submissions/
MT_DIR = os.path.dirname(SUBMISSIONS_DIR)                  # matrix-thinking/
REPO_ROOT = os.path.dirname(MT_DIR)                         # repo root

EXPRUNS = os.path.join(REPO_ROOT, "experiment-runs")
CHAPTER2 = os.path.join(MT_DIR, "chapter2")

TASKD_AGG = os.path.join(CHAPTER2, "results", "overnight_snapshots", "AGGREGATE_latest.json")
TASKE_ZDUMP_DIR = os.path.join(EXPRUNS, "2026-07-02_task_e_zdump", "task_e_40k_zdump")
STAGE0_DIR = os.path.join(EXPRUNS, "2026-07-02_stage0_waves")
EVAL_TRUNC_AGG = os.path.join(EXPRUNS, "2026-07-02_deltanet_waves", "eval_trunc",
                               "eval_trunc_d64_K32_AGGREGATE.json")

for p in (TASKD_AGG, TASKE_ZDUMP_DIR, STAGE0_DIR, EVAL_TRUNC_AGG):
    if not os.path.exists(p):
        raise FileNotFoundError(
            f"Expected archived data at {p} but it is missing. This script "
            "only plots real archived runs -- it does not fabricate data. "
            "Check that experiment-runs/ and matrix-thinking/chapter2/results/ "
            "are present (see the repo's data-archive policy in "
            "experiment-runs/README.md)."
        )

sys.path.insert(0, CHAPTER2)
import analyze_zdump as az  # noqa: E402  (numpy + stdlib only, see its own docstring)

# ---------------------------------------------------------------------------
# Colorblind-safe palette (Okabe & Ito, 2008) + redundant markers/linestyles
# ---------------------------------------------------------------------------
C_ORANGE = "#E69F00"
C_SKYBLUE = "#56B4E9"
C_GREEN = "#009E73"
C_BLUE = "#0072B2"
C_VERMILLION = "#D55E00"
C_PURPLE = "#CC79A7"
C_BLACK = "#000000"
C_GREY = "#999999"

plt.rcParams.update({
    "font.family": "serif",
    "font.size": 9,
    "axes.titlesize": 9,
    "axes.labelsize": 9,
    "xtick.labelsize": 8,
    "ytick.labelsize": 8,
    "legend.fontsize": 7.5,
    "pdf.fonttype": 42,   # embed as real text, not paths
    "ps.fonttype": 42,
    "axes.spines.top": False,
    "axes.spines.right": False,
    "axes.grid": True,
    "grid.alpha": 0.25,
    "grid.linewidth": 0.5,
})


def savefig(fig, name):
    out = os.path.join(FIG_DIR, name)
    fig.savefig(out, format="pdf", bbox_inches="tight")
    print(f"wrote {out}")
    plt.close(fig)


# ---------------------------------------------------------------------------
# Figure 1: Task D causal force-rank staircase (Table 2, tab:taskd-m3)
# Primary, pre-registered causal test (train-time force_rank_k, C1 control).
# ---------------------------------------------------------------------------
def fig_taskd_forcerank():
    with open(TASKD_AGG) as f:
        agg = json.load(f)
    m3 = agg["M3_recovered_frac@0.9_vs_forcerank"]

    cells = [
        ("d8_K4", 8, 4, C_BLUE, "o"),
        ("d16_K8", 16, 8, C_VERMILLION, "s"),
        ("d16_K12", 16, 12, C_GREEN, "^"),
    ]

    fig, axes = plt.subplots(1, 3, figsize=(6.8, 2.15), sharey=True)
    for ax, (key, d, K, color, marker) in zip(axes, cells):
        curve = m3[key]
        ks = sorted(int(k) for k in curve.keys())
        vals = [curve[str(k)] for k in ks]
        ax.plot(ks, vals, color=color, marker=marker, markersize=4,
                linewidth=1.3, clip_on=False, zorder=3)
        ax.axvline(K, color=C_GREY, linestyle="--", linewidth=1.0, zorder=1)
        ax.text(K, 1.03, r"$k{=}K$", color=C_GREY, fontsize=7,
                ha="center", va="bottom")
        ax.set_title(f"$d{{=}}{d}$, $K{{=}}{K}$", fontsize=8.5)
        ax.set_xlabel("train-time force-rank $k$")
        ax.set_xlim(1, d)
        ax.set_ylim(-0.03, 1.08)
    axes[0].set_ylabel("recovered_frac@0.9")
    fig.suptitle(
        "Primary causal test: constraining $Z$ to rank $k$ throughout training "
        "(not post-hoc truncation)",
        fontsize=8, y=1.06,
    )
    fig.tight_layout()
    savefig(fig, "fig_taskd_forcerank.pdf")


# ---------------------------------------------------------------------------
# Figure 2: Task E depth-decay -- spectral prediction vs measurement, and the
# rank-(K-1) vs rank-sufficient contrast (Table 3, tab:taske-depth; and the
# headline exact-composition result of Sec. 4.1).
# Primary, pre-registered (M2/M3 metrics; C8 eigenstructure-fidelity metric
# for the predicted curve).
# ---------------------------------------------------------------------------
def fig_taske_depth():
    fr7_path = os.path.join(TASKE_ZDUMP_DIR, "t1_matrix_permutation_K8_fr7_s2.json")
    run = az.analyze_run(fr7_path)
    predicted, _consistency = az.depth_curve_for_run(run)

    with open(fr7_path) as f:
        fr7_raw = json.load(f)
    hops = sorted(int(h) for h in list(fr7_raw["M2_in_distribution"].keys())
                  + list(fr7_raw["M3_held_out"].keys()))
    measured_cos = {h: fr7_raw["M2_in_distribution"].get(str(h), fr7_raw["M3_held_out"].get(str(h)))["mean_cos"]
                     for h in hops}
    measured_rec = {h: fr7_raw["M2_in_distribution"].get(str(h), fr7_raw["M3_held_out"].get(str(h)))["recovered_frac@0.9"]
                     for h in hops}

    # Rank-sufficient (unconstrained) seeds: 4/5 converge exactly (s1-s4);
    # s0 is the still-transitioning outlier reported in Sec. 4.1. Both are
    # plotted as real per-seed measurements, not summary numbers.
    frN_seeds = {}
    for s in range(5):
        p = os.path.join(TASKE_ZDUMP_DIR, f"t1_matrix_permutation_K8_frN_s{s}.json")
        with open(p) as f:
            d = json.load(f)
        row = {h: d["M2_in_distribution"].get(str(h), d["M3_held_out"].get(str(h)))["recovered_frac@0.9"]
               for h in hops}
        frN_seeds[s] = row
    converged_seeds = [1, 2, 3, 4]
    rank_suff_mean = [np.mean([frN_seeds[s][h] for s in converged_seeds]) for h in hops]
    outlier = [frN_seeds[0][h] for h in hops]

    xpos = np.arange(len(hops))
    xticklabels = [str(h) for h in hops]

    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(6.8, 2.3))

    ax1.plot(xpos, [predicted[h] for h in hops], color=C_BLACK, marker="o",
              markersize=4, linewidth=1.3, label="predicted (from $A$'s eigenspectrum)")
    ax1.plot(xpos, [measured_cos[h] for h in hops], color=C_VERMILLION, marker="s",
              markersize=4, linewidth=1.3, linestyle="--",
              label="measured")
    ax1.set_xticks(xpos)
    ax1.set_xticklabels(xticklabels)
    ax1.set_xlabel("hop $h$")
    ax1.set_ylabel(r"mean $\cos(Z^h k_i,\, v_{\pi^h(i)})$")
    ax1.set_title("force-rank $k{=}7{=}K{-}1$: spectrum predicts decay", fontsize=8)
    ax1.legend(loc="lower left", frameon=False)

    ax2.plot(xpos, rank_suff_mean, color=C_BLUE, marker="^", markersize=4,
              linewidth=1.3, label=r"rank-sufficient (unconstr., 4/5 seeds)")
    ax2.plot(xpos, [measured_rec[h] for h in hops], color=C_VERMILLION, marker="s",
              markersize=4, linewidth=1.3, linestyle="--", label=r"force-rank $K{-}1$")
    ax2.plot(xpos, outlier, color=C_GREY, marker="x", markersize=4,
              linewidth=1.0, linestyle=":", label="unconstr., transitioning outlier seed")
    ax2.set_xticks(xpos)
    ax2.set_xticklabels(xticklabels)
    ax2.set_xlabel("hop $h$")
    ax2.set_ylabel("recovered_frac@0.9")
    ax2.set_ylim(-0.03, 1.08)
    ax2.set_title("recoverable-fraction is the sharper depth probe", fontsize=8)
    ax2.legend(loc="lower left", frameon=False)

    fig.tight_layout()
    savefig(fig, "fig_taske_depth.pdf")


# ---------------------------------------------------------------------------
# Figure 3: The K=d/4 exactness frontier (Table 5, tab:frontier-d4).
# Primary, pre-registered (Stage 0 formal pass bar recovered_frac@0.9 > 0.7).
# ---------------------------------------------------------------------------
def fig_frontier_exactness():
    cells = [
        (32, 8, [
            os.path.join(STAGE0_DIR, "probe_100k", f"p100k_baseline_d32_K8_s{s}.json")
            for s in range(3)
        ]),
        (48, 12, [os.path.join(STAGE0_DIR, "probe_d48_100k", "p100k_baseline_d48_K12_s0.json")]),
        (64, 16, [os.path.join(STAGE0_DIR, "probe_d64_150k", "p150k_baseline_d64_K16_s0.json")]),
    ]

    ds, cos_means, cos_pts, rec_means, rec_pts = [], [], [], [], []
    for d, K, paths in cells:
        cos_vals, rec_vals = [], []
        for p in paths:
            with open(p) as f:
                r = json.load(f)
            cos_vals.append(r["mean_cos"])
            rec_vals.append(r["recovered_frac@0.9"])
        ds.append(d)
        cos_means.append(np.mean(cos_vals))
        cos_pts.append(cos_vals)
        rec_means.append(np.mean(rec_vals))
        rec_pts.append(rec_vals)

    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(6.8, 2.3))

    for ax, means, pts, ylabel, title in (
        (ax1, cos_means, cos_pts, r"mean $\cos(Z{\cdot}\mathrm{key}, \mathrm{value})$",
         "cosine recovery"),
        (ax2, rec_means, rec_pts, "recovered_frac@0.9", "exact-match recovery (harsher)"),
    ):
        for d, pt in zip(ds, pts):
            ax.scatter([d] * len(pt), pt, color=C_SKYBLUE, s=14, zorder=2,
                       label="per-seed" if d == ds[0] else None)
        ax.plot(ds, means, color=C_BLUE, marker="o", markersize=5, linewidth=1.5,
                zorder=3, label="mean")
        ax.axhline(1.0, color=C_GREY, linestyle=":", linewidth=1.0, label="$d{=}16$ ref. (exact)")
        if title.startswith("exact"):
            ax.axhline(0.7, color=C_VERMILLION, linestyle="--", linewidth=1.0,
                       label="pre-registered pass bar")
        ax.set_xticks(ds)
        ax.set_xticklabels([f"$d{{=}}{d}$\n$K{{=}}{d//4}$" for d in ds])
        ax.set_ylabel(ylabel)
        ax.set_title(title, fontsize=8)
        ax.set_ylim(-0.03, 1.12)
        ax.legend(loc="lower left", frameon=True, framealpha=0.95,
                  edgecolor="none", fontsize=6.5)

    fig.suptitle(
        r"$K{=}d/4$ exactness frontier at fixed encoder width $h{=}64$; "
        "budget: 100K steps ($d{=}32,48$), 150K ($d{=}64$)",
        fontsize=8, y=1.06,
    )
    fig.tight_layout()
    savefig(fig, "fig_frontier_exactness.pdf")


# ---------------------------------------------------------------------------
# Figure 4 (supplementary/illustrative): eval-time SVD-truncation staircase,
# d=64, K=32. NOT behind any table in the main text -- included as a
# mechanism illustration, distinct in kind from the primary causal test
# (Fig. 1, which forces rank at TRAIN time throughout, not post-hoc).
# ---------------------------------------------------------------------------
def fig_eval_trunc_staircase():
    with open(EVAL_TRUNC_AGG) as f:
        agg = json.load(f)
    k_grid = agg["k_grid"]
    h_grid = agg["h_grid"]
    K = 32

    agg_vals = collections.defaultdict(list)
    for ps in agg["per_seed"]:
        for h, kd in ps["staircase"].items():
            for k, m in kd.items():
                agg_vals[(int(h), int(k))].append(m["recovered_frac@0.9"])

    show_h = [1, 3, 7, 21]
    colors = [C_BLUE, C_SKYBLUE, C_ORANGE, C_VERMILLION]
    markers = ["o", "s", "^", "D"]

    fig, ax = plt.subplots(1, 1, figsize=(4.4, 2.5))
    for h, color, marker in zip(show_h, colors, markers):
        vals = [np.mean(agg_vals[(h, k)]) for k in k_grid]
        ax.plot(k_grid, vals, color=color, marker=marker, markersize=4,
                linewidth=1.3, label=f"$h{{=}}{h}$")
    ax.axvline(K, color=C_GREY, linestyle="--", linewidth=1.0, zorder=1)
    ax.text(K, 1.05, r"$k{=}K{=}32$", color=C_GREY, fontsize=7, ha="center")
    ax.set_xlabel("eval-time SVD-truncation rank $k$")
    ax.set_ylabel("recovered_frac@0.9")
    ax.set_ylim(-0.03, 1.12)
    ax.set_title(
        "Supplementary: post-hoc truncation, $d{=}64,K{=}32$\n"
        "(illustrative -- not the paper's primary causal instrument)",
        fontsize=7.5,
    )
    ax.legend(loc="lower right", frameon=False, title="hop depth", ncol=1)
    fig.tight_layout()
    savefig(fig, "fig_eval_trunc_staircase.pdf")


if __name__ == "__main__":
    fig_taskd_forcerank()
    fig_taske_depth()
    fig_frontier_exactness()
    fig_eval_trunc_staircase()
    print("All figures regenerated from archived JSONs.")
