#!/usr/bin/env python3
"""98M FRONTIER SEED THICKENING -- seeds 3,4,5 at K=36/40, both recipes.
PI directive 2026-08-23. 12 cells, ids 0330-0341.

NO NEW DESIGN. This imports the AUDITED generator (gen_job_specs.py) and calls
its OWN `spec()` with new seeds and new ids, so every field -- hypothesis,
ladder, bands, param literal, validity_check, notes -- is produced by the same
code that produced the frontier wave of record (0140-0151, EXPERIMENT_LOG
2026-08-22 #7). Only three things differ:

  1. the SEED integer (3,4,5 instead of 0,1,2);
  2. the ID block (0330-0341, collision-free against full history);
  3. the CEILING, re-priced from the MEASURED per-(K, recipe) cost of the
     wave of record instead of the as-run flat `--ceiling-gpuh 6.0`.

It is a SEPARATE entry point from gen_job_specs.main()/main_frontier() for that
module's own stated reason: "so that generating the frontier wave cannot
rewrite, resurrect or renumber a spec belonging to the completed wave."
Nothing here writes into gen_job_specs' own job_specs/ directory.

WHAT IT BUYS. The breadth frontier's per-K cells go from n=3 to n=6, and the
within-K ordering strata from 9 seed-pairs to 36 -- the same thickening the
392M wave gets, on the reference side of the cross-scale comparison.

THIS WAVE CHANGES NO VERDICT. The frontier bands were pinned and adjudicated at
n=3 (#3 pre-registration, #7 adjudication: NO FRONTIER FOUND, curve spans
(12,13)->(40,41)). The wave adds precision -- CIs and LOSO robustness -- and is
reported as n=6 updates to the SAME tables. If a pinned verdict FLIPS at n=6
that is a FINDING requiring its own EXPERIMENT_LOG entry, never a silent update.
"""
from __future__ import annotations

import argparse
import collections
import glob
import json
import os
import re
import sys

_HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, _HERE)
import gen_job_specs as G    # noqa: E402  (the AUDITED generator; its spec() is reused verbatim)

OUT = os.path.join(_HERE, "job_specs_thicken")
FRONTIER_K = (40, 36)        # longest-first, per the dispatch-order convention
RECIPES = ("primary", "compB")
SEEDS = (3, 4, 5)
ID_START = 330
CEILING_MULT = 1.5
ARCHIVES = ("2026-08-22_kscaling_frontier", "2026-08-22_kscaling_sweep")


def measured(repo_root: str) -> dict:
    """MEASURED per-(K, recipe) cost from the 98M cells of record."""
    agg = collections.defaultdict(list)
    for a in ARCHIVES:
        for p in sorted(glob.glob(os.path.join(repo_root, "experiment-runs", a, "*.json"))):
            try:
                d = json.load(open(p))
            except Exception:                       # noqa: BLE001
                continue
            if d.get("mode") != "calibration" or d.get("status") != "COMPLETED":
                continue
            ks = d.get("kscaling") or {}
            k = int(ks.get("K", 0))
            if k not in FRONTIER_K:
                continue
            r = "primary" if d["config"]["freeze_entity_adapter"] else "compB"
            agg[(k, r)].append(d.get("gpu_h") or (d.get("elapsed_s") or 0) / 3600.0)
    want = {(k, r) for k in FRONTIER_K for r in RECIPES}
    assert set(agg) == want, f"expected {sorted(want)} in the 98M archives, got {sorted(agg)}"
    return {k: sum(v) / len(v) for k, v in agg.items()}


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--repo-root", default=os.path.dirname(os.path.dirname(_HERE)))
    ap.add_argument("--queue-ids", default=None)
    args = ap.parse_args()
    real = measured(args.repo_root)
    os.makedirs(OUT, exist_ok=True)

    written, n = [], ID_START
    for k in FRONTIER_K:
        for recipe in RECIPES:
            for seed in SEEDS:
                # THE AUDITED GENERATOR'S OWN spec(), unchanged.
                sp = G.spec(f"{n:04d}_ncr_kscaling_thicken_K{k}_{recipe}_s{seed}",
                            k, recipe, seed, "frontier")
                marg = real[(k, recipe)]
                ceil_v = round(CEILING_MULT * marg, 3)
                old_cell = f"kscaling_K{k}_{recipe}_s{seed}"
                new_cell = f"kscaling_thicken_K{k}_{recipe}_s{seed}"
                sp["cmd"] = re.sub(r"--ceiling-gpuh [0-9.]+", f"--ceiling-gpuh {ceil_v}",
                                   sp["cmd"]).replace(old_cell, new_cell)
                sp["validity_check"] = sp["validity_check"].replace(old_cell, new_cell)
                sp["output_dir"] = sp["output_dir"]
                sp["gpu_h_estimate"] = round(marg, 3)
                sp["tier"] = "kscaling_thicken"
                sp["notes"] = (
                    "CANDIDATE -- NOT queue-eligible; the coordinator stages on the build "
                    "receipt. 98M FRONTIER SEED-THICKENING (PI 2026-08-23). Generated by the "
                    "AUDITED gen_job_specs.spec() itself -- byte-pattern-identical to the "
                    "frontier wave of record (0140-0151, EXPERIMENT_LOG 2026-08-22 #7) modulo "
                    "the seed integer, the id, the cell id and the ceiling. NO NEW DESIGN. "
                    f"CEILING RE-PRICED FROM MEASUREMENT: 1.5 x the MEASURED per-(K, recipe) "
                    f"cost of the wave of record ({marg:.4f} GPU-h) = {ceil_v} GPU-h, replacing "
                    f"the as-run flat --ceiling-gpuh 6.0 (which carried 5.3x headroom and never "
                    f"tripped, but is not a measured number). This wave takes the frontier's "
                    "per-K cells from n=3 to n=6 and the within-K ordering strata from 9 "
                    "seed-pairs to 36. IT CHANGES NO VERDICT: the bands were pinned and "
                    "adjudicated at n=3 (#3 pre-registration, #7 NO FRONTIER FOUND); the wave "
                    "adds precision (CIs, LOSO robustness) and is reported as n=6 updates to "
                    "the SAME tables. A pinned verdict FLIPPING at n=6 is a FINDING requiring "
                    "its own EXPERIMENT_LOG entry, never a silent update. Runs from the "
                    "RETAINED kscaling tree (~/ncr_kscaling), which design sec 3.5 requires be "
                    "kept alongside the scaleaxis tree; a cross-tree invocation is the failure "
                    "that note exists to prevent. " + sp["notes"])
                sp["thickening"] = {
                    "directive": "PI 2026-08-23 -- seed thickening of the flagship's central tables",
                    "scale": "98m", "K": k, "recipe": recipe, "seed": seed,
                    "sibling_seeds_of_record": [0, 1, 2],
                    "takes_n_from": 3, "takes_n_to": 6,
                    "within_K_pairs_from": 9, "within_K_pairs_to": 36,
                    "generator": "gen_job_specs.spec() (audited), reused verbatim",
                    "measured_gpu_h": round(marg, 4), "ceiling_gpuh": ceil_v,
                    "changes_no_verdict": True,
                    "queue_eligible": False,
                }
                written.append(sp)
                n += 1

    ids = [s["id"][:4] for s in written]
    assert len(written) == 12 and len(set(ids)) == 12, ids
    assert ids == [f"{i:04d}" for i in range(ID_START, ID_START + 12)], ids
    if args.queue_ids:
        existing = {ln.strip()[:4] for ln in open(args.queue_ids) if ln.strip()}
        clash = sorted(set(ids) & existing)
        assert not clash, f"ID COLLISION with queue history: {clash}"
    for s in written:
        with open(os.path.join(OUT, s["id"] + ".json"), "w") as f:
            json.dump(s, f, indent=1)

    tot = sum(s["gpu_h_estimate"] for s in written)
    print(f"wrote {len(written)} CANDIDATE 98M frontier-thickening specs to {OUT} "
          f"({ids[0]}-{ids[-1]})")
    print(f"  K in {FRONTIER_K} x {RECIPES} x seeds {SEEDS}")
    print(f"  MEASURED ledger: {tot:.2f} GPU-h; ceilings "
          f"{sorted({s['thickening']['ceiling_gpuh'] for s in written})}")
    print("QUEUE-ELIGIBLE: NO.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
